self-hosted-runner:
  labels:
    - altinity-on-demand
    - altinity-in-fsn1
    - altinity-in-ash
    - altinity-image-arm-app-docker-ce
    - altinity-image-x86-app-docker-ce
    - altinity-type-cax41
    - altinity-type-cpx41
    - altinity-type-cpx51
    - altinity-type-ccx53
