name: Checkout submodules
description: 'Checkout submodules'
inputs:
  submodules-depth:
    description: The depth of submodules to checkout
    required: true
    default: 1
runs:
  steps:
    - name: Checkout submodules
      shell: bash
      run: |
        git -C "$GITHUB_WORKSPACE" submodule sync
        git -C "$GITHUB_WORKSPACE" submodule init
        git config --file "$GITHUB_WORKSPACE/.gitmodules" --null --get-regexp path | \
            sed -z 's|.*\n||' | \
            xargs --max-procs=100 --null --no-run-if-empty --max-args=1 \
                $GITHUB_WORKSPACE/.github/retry.sh 60 5 "git -C \"$GITHUB_WORKSPACE\" submodule update --depth=\"${{ inputs.submodules-depth }}\" --single-branch"
