from pathlib import Path

from ci.jobs import source_upload
from ci.jobs.scripts import clickhouse_version
from ci.jobs.scripts.clickhouse_version import CHVersion
from ci.jobs.scripts.workflow_hooks import version_log


FLAVOURED_VERSION_FILE = """\
SET(VERSION_REVISION 54513)
SET(VERSION_MAJOR 26)
SET(VERSION_MINOR 8)
SET(VERSION_PATCH 1)
SET(VERSION_GITHASH 0123456789012345678901234567890123456789)
SET(VERSION_DESCRIBE v26.8.1.10001.altinitytest)
SET(VERSION_STRING 26.8.1.10001.altinitytest)
SET(VERSION_TWEAK 10001)
SET(VERSION_FLAVOUR altinitytest)
"""


def use_version_file(monkeypatch, tmp_path: Path, content: str) -> Path:
    path = tmp_path / "autogenerated_versions.txt"
    path.write_text(content, encoding="utf-8")
    monkeypatch.setattr(clickhouse_version, "FILE_WITH_VERSION_PATH", str(path))
    return path


def test_flavoured_current_version_uses_pinned_file(monkeypatch, tmp_path):
    use_version_file(monkeypatch, tmp_path, FLAVOURED_VERSION_FILE)
    monkeypatch.setattr(
        clickhouse_version,
        "_tweak_from_git",
        lambda _: (_ for _ in ()).throw(AssertionError("Git tweak must not be read")),
    )
    monkeypatch.setattr(
        clickhouse_version.Shell,
        "get_output",
        lambda *_args, **_kwargs: (_ for _ in ()).throw(
            AssertionError("Git SHA must not replace the pinned file SHA")
        ),
    )

    version = CHVersion.get_current_version()

    assert version.string == "26.8.1.10001.altinitytest"
    assert version.describe == "v26.8.1.10001.altinitytest"
    assert version.tweak == 10001
    assert version.flavour == "altinitytest"
    assert version.githash == "0123456789012345678901234567890123456789"


def test_flavoured_release_version_round_trips_through_dict(monkeypatch, tmp_path):
    use_version_file(monkeypatch, tmp_path, FLAVOURED_VERSION_FILE)

    version = CHVersion.get_release_version()
    restored = CHVersion.from_dict(version.to_dict())

    assert restored.to_dict() == version.to_dict()
    assert restored.to_dict()["flavour"] == "altinitytest"


def test_flavoured_version_write_preserves_altinity_fields(monkeypatch, tmp_path):
    path = use_version_file(monkeypatch, tmp_path, FLAVOURED_VERSION_FILE)

    CHVersion.get_release_version().write()

    content = path.read_text(encoding="utf-8")
    assert "SET(VERSION_TWEAK 10001)" in content
    assert "SET(VERSION_FLAVOUR altinitytest)" in content
    assert "SET(VERSION_STRING 26.8.1.10001.altinitytest)" in content
    assert "SET(VERSION_DESCRIBE v26.8.1.10001.altinitytest)" in content


def test_unflavoured_current_version_keeps_git_derived_tweak(monkeypatch, tmp_path):
    use_version_file(
        monkeypatch,
        tmp_path,
        """\
SET(VERSION_REVISION 54513)
SET(VERSION_MAJOR 26)
SET(VERSION_MINOR 8)
SET(VERSION_PATCH 1)
SET(VERSION_GITHASH release-sha)
SET(VERSION_DESCRIBE v26.8.1.1-lts)
SET(VERSION_STRING 26.8.1.1)
""",
    )
    monkeypatch.setattr(clickhouse_version, "_tweak_from_git", lambda _: 42)
    monkeypatch.setattr(
        clickhouse_version.Shell, "get_output", lambda *_args, **_kwargs: "head-sha"
    )

    version = CHVersion.get_current_version()

    assert version.string == "26.8.1.42"
    assert version.describe == "v26.8.1.42-lts"
    assert version.flavour == ""
    assert version.githash == "head-sha"


class FakeInfo:
    pr_number = 123
    pr_url = "https://example.test/pull/123"
    sha = "pr-sha"
    commit_url = "https://example.test/commit/pr-sha"
    git_branch = "feature"
    workflow_name = "PullRequest"


def test_pr_build_preserves_flavoured_tweak(monkeypatch):
    version = CHVersion(
        26,
        8,
        1,
        54513,
        tweak=10001,
        githash="file-sha",
        version_type="altinitytest",
        flavour="altinitytest",
    )
    monkeypatch.setattr(
        CHVersion, "get_current_version", classmethod(lambda cls, **kwargs: version)
    )

    assert version_log._build_version(FakeInfo()).string == (
        "26.8.1.10001.altinitytest"
    )


def test_pr_build_still_pins_unflavoured_tweak(monkeypatch):
    version = CHVersion(
        26,
        8,
        1,
        54513,
        tweak=42,
        githash="file-sha",
        version_type="lts",
    )
    monkeypatch.setattr(
        CHVersion, "get_current_version", classmethod(lambda cls, **kwargs: version)
    )

    assert version_log._build_version(FakeInfo()).string == "26.8.1.1"


def test_version_log_mirrors_version_into_workflow_custom_data(monkeypatch):
    stored = {}
    config = type("Config", (), {"custom_data": {}, "dump": lambda self: self})()

    class FakeRunConfig:
        @classmethod
        def from_fs(cls, workflow_name):
            assert workflow_name == "PullRequest"
            return config

    class FakeCIDB:
        def insert_json(self, table, json_str):
            stored["cidb"] = (table, json_str)

    class FakeVersion:
        string = "26.8.1.10001.altinitytest"

        def to_dict(self):
            return {"string": self.string, "flavour": "altinitytest", "tweak": 10001}

        def store_version_data_in_ci_pipeline(self):
            stored["kv"] = self.to_dict()

    monkeypatch.setattr(version_log, "Info", lambda: FakeInfo())
    monkeypatch.setattr(version_log, "RunConfig", FakeRunConfig, raising=False)
    monkeypatch.setattr(version_log, "CIDBCluster", FakeCIDB)
    monkeypatch.setattr(version_log, "_build_version", lambda _info: FakeVersion())
    monkeypatch.setattr(version_log.Shell, "check", lambda *_args, **_kwargs: True)
    monkeypatch.setattr(
        version_log.Shell, "get_output", lambda *_args, **_kwargs: "parent-sha"
    )

    version_log._add_build_to_version_history()

    assert stored["kv"] == config.custom_data["version"]
    assert stored["cidb"][0] == "version_history"


def test_source_upload_prefers_pipeline_version(monkeypatch):
    pipeline_version = CHVersion(
        26,
        8,
        1,
        54513,
        tweak=1,
        githash="pr-sha",
        version_type="testing",
    )
    monkeypatch.setattr(
        CHVersion,
        "get_current_version_from_ci_pipeline",
        classmethod(lambda cls: pipeline_version),
    )
    monkeypatch.setattr(
        CHVersion,
        "get_current_version",
        classmethod(
            lambda cls, **kwargs: (_ for _ in ()).throw(
                AssertionError("repo fallback must not replace the pipeline version")
            )
        ),
    )

    assert source_upload.get_version().string == "26.8.1.1"
