import os
import sys
from pathlib import Path

import pytest

from ci.jobs import source_upload
from ci.jobs.scripts import clickhouse_version
from ci.jobs.scripts.clickhouse_version import CHVersion
from ci.jobs.scripts.workflow_hooks import version_log

# `version_helper` imports sibling modules from `tests/ci` by bare name.
_CI_DIR = os.path.abspath(
    os.path.join(os.path.dirname(__file__), "..", "..", "tests", "ci")
)
sys.path.insert(0, _CI_DIR)
try:
    from version_helper import check_tag_version  # type: ignore[import-not-found]
finally:
    sys.path.remove(_CI_DIR)


# Committed layout: upstream DESCRIBE/STRING, Altinity TWEAK/FLAVOUR appended.
UPSTREAM_BLOCK_VERSION_FILE = """\
SET(VERSION_REVISION 54513)
SET(VERSION_MAJOR 26)
SET(VERSION_MINOR 8)
SET(VERSION_PATCH 1)
SET(VERSION_GITHASH 0123456789012345678901234567890123456789)
SET(VERSION_DESCRIBE v26.8.1.1-lts)
SET(VERSION_STRING 26.8.1.1)
# end of autochange

SET(VERSION_TWEAK 10001)
SET(VERSION_FLAVOUR altinitytest)
"""


def use_version_file(monkeypatch, tmp_path: Path, content: str) -> Path:
    path = tmp_path / "autogenerated_versions.txt"
    path.write_text(content, encoding="utf-8")
    monkeypatch.setattr(clickhouse_version, "FILE_WITH_VERSION_PATH", str(path))
    return path


def test_flavoured_current_version_uses_pinned_file(monkeypatch, tmp_path):
    use_version_file(monkeypatch, tmp_path, UPSTREAM_BLOCK_VERSION_FILE)
    monkeypatch.setattr(
        clickhouse_version,
        "_tweak_from_git",
        lambda _: (_ for _ in ()).throw(AssertionError("Git tweak must not be read")),
    )
    monkeypatch.setattr(
        clickhouse_version.Shell,
        "get_output",
        lambda *_args, **_kwargs: (_ for _ in ()).throw(
            AssertionError("Git SHA must not replace the pinned file SHA")
        ),
    )

    version = CHVersion.get_current_version()

    assert version.string == "26.8.1.10001.altinitytest"
    assert version.describe == "v26.8.1.10001.altinitytest"
    assert version.tweak == 10001
    assert version.flavour == "altinitytest"
    assert version.githash == "0123456789012345678901234567890123456789"


def test_flavoured_release_version_round_trips_through_dict(monkeypatch, tmp_path):
    use_version_file(monkeypatch, tmp_path, UPSTREAM_BLOCK_VERSION_FILE)

    version = CHVersion.get_release_version()
    restored = CHVersion.from_dict(version.to_dict())

    assert restored.to_dict() == version.to_dict()
    assert restored.to_dict()["flavour"] == "altinitytest"


def test_flavoured_version_write_preserves_altinity_fields(monkeypatch, tmp_path):
    path = use_version_file(monkeypatch, tmp_path, UPSTREAM_BLOCK_VERSION_FILE)

    CHVersion.get_release_version().write()

    content = path.read_text(encoding="utf-8")
    assert "SET(VERSION_TWEAK 10001)" in content
    assert "SET(VERSION_FLAVOUR altinitytest)" in content
    assert "SET(VERSION_STRING 26.8.1.10001.altinitytest)" in content
    assert "SET(VERSION_DESCRIBE v26.8.1.10001.altinitytest)" in content


class FakeInfo:
    pr_number = 123
    pr_url = "https://example.test/pull/123"
    sha = "pr-sha"
    commit_url = "https://example.test/commit/pr-sha"
    git_branch = "feature"
    workflow_name = "PullRequest"


def test_pr_build_preserves_flavoured_tweak(monkeypatch):
    version = CHVersion(
        26,
        8,
        1,
        54513,
        tweak=10001,
        githash="file-sha",
        version_type="altinitytest",
        flavour="altinitytest",
    )
    monkeypatch.setattr(
        CHVersion, "get_current_version", classmethod(lambda cls, **kwargs: version)
    )

    assert version_log._build_version(FakeInfo()).string == (
        "26.8.1.10001.altinitytest"
    )


def test_source_upload_prefers_pipeline_version(monkeypatch):
    pipeline_version = CHVersion(
        26,
        8,
        1,
        54513,
        tweak=1,
        githash="pr-sha",
        version_type="testing",
    )
    monkeypatch.setattr(
        CHVersion,
        "get_current_version_from_ci_pipeline",
        classmethod(lambda cls: pipeline_version),
    )
    monkeypatch.setattr(
        CHVersion,
        "get_current_version",
        classmethod(
            lambda cls, **kwargs: (_ for _ in ()).throw(
                AssertionError("repo fallback must not replace the pipeline version")
            )
        ),
    )

    assert source_upload.get_version().string == "26.8.1.1"


def test_tag_build_takes_flavour_from_tag(monkeypatch, tmp_path):
    use_version_file(monkeypatch, tmp_path, UPSTREAM_BLOCK_VERSION_FILE)
    monkeypatch.setenv("GITHUB_REF_TYPE", "tag")
    monkeypatch.setenv("GITHUB_REF_NAME", "v26.8.1.10001.altinitystable")

    info = FakeInfo()
    info.pr_number = 0
    version = version_log._build_version(info)

    assert version.string == "26.8.1.10001.altinitystable"
    assert version.describe == "v26.8.1.10001.altinitystable"
    assert version.to_dict()["flavour"] == "altinitystable"


def _tag_version_file(tmp_path: Path, tweak: int = 10001) -> Path:
    path = tmp_path / "autogenerated_versions.txt"
    path.write_text(
        UPSTREAM_BLOCK_VERSION_FILE.replace("10001", str(tweak)), encoding="utf-8"
    )
    return path


@pytest.mark.parametrize(
    "tweak,flavour",
    [
        (10001, "altinitystable"),
        (20001, "altinityantalya"),
        (30001, "altinityfips"),
    ],
)
def test_check_tag_version_accepts_matching_track(tmp_path, tweak, flavour):
    check_tag_version(
        f"v26.8.1.{tweak}.{flavour}", _tag_version_file(tmp_path, tweak)
    )


@pytest.mark.parametrize(
    "tag",
    [
        "v26.8.1.10001.altinityantalya",
        "v26.8.1.10002.altinitystable",
        "v26.8.1.10001.altinitytest",
        "v26.8.1.1-lts",
    ],
)
def test_check_tag_version_rejects_mismatched_tag(tmp_path, tag):
    with pytest.raises(ValueError):
        check_tag_version(tag, _tag_version_file(tmp_path))
