protobuf_generate_cpp(clickhouse_cas_proto_sources clickhouse_cas_proto_headers cas_root_shard.proto)

add_library(clickhouse_cas_proto ${clickhouse_cas_proto_headers} ${clickhouse_cas_proto_sources})
target_include_directories(clickhouse_cas_proto SYSTEM PUBLIC ${CMAKE_CURRENT_BINARY_DIR})
target_link_libraries(clickhouse_cas_proto PUBLIC ch_contrib::protoc)
# Ignore warnings while compiling protobuf-generated *.pb.h and *.pb.cpp files.
target_compile_options(clickhouse_cas_proto PRIVATE "-w")
# Disable clang-tidy for protobuf-generated *.pb.h and *.pb.cpp files.
set_target_properties(clickhouse_cas_proto PROPERTIES CXX_CLANG_TIDY "")
