-- Tags: no-fasttest
-- ^ DataSketches is not built in fast-test builds.

-- Fixtures were generated by Apache DataSketches C++, with a varint length prefix.
-- These checks pin compatibility with external producers and consumers.

SELECT 'import sketches built outside ClickHouse';

-- lg_k = 12, HLL_4, `hll_sketch::update` on `uint64_t` values over 0..4. Coupon list mode.
SELECT finalizeAggregation(CAST(unhex('1C0201070C03080500CBD7C2042BF2FB06862FF90D7581660781BC5D06'), 'AggregateFunction(uniqApacheHLL, UInt64)'));

-- External sketches over 0..4 and 3..7 overlap with ClickHouse values 6..10.
SELECT uniqApacheHLLMerge(s) FROM
(
    SELECT CAST(unhex('1C0201070C03080500CBD7C2042BF2FB06862FF90D7581660781BC5D06'), 'AggregateFunction(uniqApacheHLL, UInt64)') AS s
    UNION ALL
    SELECT CAST(unhex('1C0201070C030805007581660781BC5D067B65E608FC2D420AC1E91705'), 'AggregateFunction(uniqApacheHLL, UInt64)') AS s
    UNION ALL
    SELECT uniqApacheHLLState(number) AS s FROM numbers(6, 5)
);

-- lg_k = 4, HLL_4, 100 distinct values. Dense HLL mode rather than a coupon list.
SELECT finalizeAggregation(CAST(unhex('300A0107040008020215EB1DC787F15440000000000000FB3F000000000000000003000000000000000251214121031025'), 'AggregateFunction(uniqApacheHLL(4), UInt64)'));

-- lg_k = 14, HLL_8: the non-default parameters are carried by the state type.
SELECT finalizeAggregation(CAST(unhex('1C0201070E03080508CBD7C2042BF2FB06862FF90D7581660781BC5D06'), 'AggregateFunction(uniqApacheHLL(14, \'HLL_8\'), UInt64)'));

-- An externally produced empty sketch.
SELECT finalizeAggregation(CAST(unhex('080201070C030C0000'), 'AggregateFunction(uniqApacheHLL, UInt64)'));

SELECT 'types wider than the 8 bytes update(long) takes';

-- Canonical bytes of `UUID` values 00000000-0000-0000-0000-00000000000{0..4}.
SELECT hex(toString(uniqApacheHLLState(toUUID(concat('00000000-0000-0000-0000-00000000000', toString(number))))))
     = '1C0201070C0308050050C94D05854BD10ADB8CBD053C56FB07F8FDB206'
FROM numbers(5) SETTINGS max_threads = 1;

-- The same for 2001:db8::1 .. ::5, which ClickHouse already holds in network order.
SELECT hex(toString(uniqApacheHLLState(toIPv6(concat('2001:db8::', hex(number + 1))))))
     = '1C0201070C0308050018216E09FAB4750F52D5BB07DFBDE30A79BC9D0B'
FROM numbers(5) SETTINGS max_threads = 1;

SELECT 'DateTime64 is hashed as the epoch time it counts';

-- Epoch milliseconds for 2020-01-01 00:00:00.000 UTC and the next four seconds.
SELECT hex(toString(uniqApacheHLLState(toDateTime64('2020-01-01 00:00:00.000', 3, 'UTC') + number)))
     = '1C0201070C0308050001D4B019CBDD6F1059310D0E833938083897B304'
FROM numbers(5) SETTINGS max_threads = 1;

SELECT 'export sketches for consumption outside ClickHouse';

-- Use one thread to keep coupon ordering deterministic.
SELECT hex(toString(uniqApacheHLLState(number))) = '1C0201070C03080500CBD7C2042BF2FB06862FF90D7581660781BC5D06' FROM numbers(5) SETTINGS max_threads = 1;
SELECT hex(toString(uniqApacheHLLState(14, 'HLL_8')(number))) = '1C0201070E03080508CBD7C2042BF2FB06862FF90D7581660781BC5D06' FROM numbers(5) SETTINGS max_threads = 1;

-- Importing an external sketch and exporting it again must reproduce it byte for byte.
SELECT hex(toString(uniqApacheHLLMergeState(s))) = '1C0201070C03080500CBD7C2042BF2FB06862FF90D7581660781BC5D06'
FROM (SELECT CAST(unhex('1C0201070C03080500CBD7C2042BF2FB06862FF90D7581660781BC5D06'), 'AggregateFunction(uniqApacheHLL, UInt64)') AS s)
SETTINGS max_threads = 1;

SELECT 'store and merge states with a different lg_k';

DROP TABLE IF EXISTS hll_interop_states;
CREATE TABLE hll_interop_states (k UInt8, s AggregateFunction(uniqApacheHLL, UInt64)) ENGINE = AggregatingMergeTree ORDER BY k;
INSERT INTO hll_interop_states SELECT number % 4 AS k, uniqApacheHLLState(8)(number) FROM numbers(20) GROUP BY k;
OPTIMIZE TABLE hll_interop_states FINAL;
-- Small enough to stay in coupon mode, so the union is exact regardless of how it was partitioned.
SELECT uniqApacheHLLMerge(s) FROM hll_interop_states;
DROP TABLE hll_interop_states;

SELECT 'merging states built with a different lg_k';
-- Downsampling and building at the lower resolution must produce the same union estimate.
SELECT
    (SELECT uniqApacheHLLMerge(8)(s) FROM (SELECT uniqApacheHLLState(number)    AS s FROM numbers(100000) GROUP BY number % 17))
  = (SELECT uniqApacheHLLMerge(8)(s) FROM (SELECT uniqApacheHLLState(8)(number) AS s FROM numbers(100000) GROUP BY number % 17));

-- Downsampling must also reduce the serialized state size.
SELECT
    length(toString(uniqApacheHLLMergeState(8)(s))) < length(toString(uniqApacheHLLMergeState(s))) / 8
FROM (SELECT uniqApacheHLLState(number) AS s FROM numbers(100000) GROUP BY number % 17);

SELECT 'relabelling with CAST does not rescale';
SELECT
    finalizeAggregation(CAST(s, 'AggregateFunction(uniqApacheHLL(8), UInt64)')) = finalizeAggregation(s),
    length(toString(CAST(s, 'AggregateFunction(uniqApacheHLL(8), UInt64)'))) = length(toString(s))
FROM (SELECT uniqApacheHLLState(number) AS s FROM numbers(1000));

SELECT 'only the parameters are interchangeable';
SELECT CAST(uniqApacheHLLState(toString(number)), 'AggregateFunction(uniqApacheHLL, UInt64)') FROM numbers(10); -- { serverError CANNOT_CONVERT_TYPE }
SELECT CAST(uniqThetaState(number), 'AggregateFunction(uniqApacheHLL, UInt64)') FROM numbers(10); -- { serverError CANNOT_CONVERT_TYPE }
