include(${PROJECT_SOURCE_DIR}/cmake/autogenerated_versions.txt)

set(VERSION_EXTRA "" CACHE STRING "")
set(VERSION_TWEAK "" CACHE STRING "")

# NOTE (strtgbb): VERSION_STRING/VERSION_DESCRIBE in autogenerated_versions.txt are left as upstream's
# to avoid merge conflicts; Altinity's VERSION_TWEAK and VERSION_FLAVOUR are set after the autochange block
if (VERSION_FLAVOUR)
    set (VERSION_STRING "${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_PATCH}.${VERSION_TWEAK}.${VERSION_FLAVOUR}")
    set (VERSION_DESCRIBE "v${VERSION_STRING}")
endif ()

if (VERSION_EXTRA)
    string(CONCAT VERSION_STRING ${VERSION_STRING} "." ${VERSION_EXTRA})
endif ()

set (VERSION_NAME "${PROJECT_NAME}")
set (VERSION_FULL "${VERSION_NAME} ${VERSION_STRING}")
set (VERSION_SO "${VERSION_STRING}")
set (VERSION_STRING_SHORT "${VERSION_MAJOR}.${VERSION_MINOR}")

# VERSION_STRING may carry a non-numeric flavour suffix (e.g. ".altinityantalya"), sometimes a purely numeric variant is needed.
if (NOT VERSION_STRING MATCHES "^([0-9]+(\\.[0-9]+)?(\\.[0-9]+)?(\\.[0-9]+)?)(\\.|$)")
    message (FATAL_ERROR "Cannot extract a numeric version from VERSION_STRING '${VERSION_STRING}'")
endif ()
set (VERSION_STRING_WITHOUT_FLAVOUR "${CMAKE_MATCH_1}")

math (EXPR VERSION_INTEGER "${VERSION_PATCH} + ${VERSION_MINOR}*1000 + ${VERSION_MAJOR}*1000000")

if(CLICKHOUSE_OFFICIAL_BUILD)
    set(VERSION_OFFICIAL " (altinity build)")
endif()
