name: JepsenWorkflow
env:
  # Force the stdout and stderr streams to be unbuffered
  PYTHONUNBUFFERED: 1
concurrency:
  group: jepsen
on: # yamllint disable-line rule:truthy
#   schedule:
#     - cron: '0 */6 * * *'
  workflow_dispatch:
  workflow_call:
jobs:
  KeeperJepsenRelease:
    runs-on: [self-hosted, altinity-on-demand, altinity-type-cpx41, altinity-in-ash, altinity-image-x86-app-docker-ce]
    steps:
      - name: Set envs
        run: |
          cat >> "$GITHUB_ENV" << 'EOF'
          TEMP_PATH=${{runner.temp}}/keeper_jepsen
          REPO_COPY=${{runner.temp}}/keeper_jepsen/ClickHouse
          EOF
      - name: Check out repository code
        uses: Altinity/checkout@34c90ad008fe1469182f3637d3de4766aa10a5c7
        with:
          clear-repository: true
          fetch-depth: 0
      - name: Jepsen Test
        run: |
          sudo rm -fr "$TEMP_PATH"
          mkdir -p "$TEMP_PATH"
          cp -r "$GITHUB_WORKSPACE" "$TEMP_PATH"
          cd "$REPO_COPY/tests/ci"
          python3 jepsen_check.py keeper
      - name: Cleanup
        if: always()
        run: |
          docker ps --quiet | xargs --no-run-if-empty docker kill ||:
          docker ps --all --quiet | xargs --no-run-if-empty docker rm -f ||:
          sudo rm -fr "$TEMP_PATH"
  # ServerJepsenRelease:
  #   runs-on: [self-hosted, altinity-on-demand, altinity-type-cpx41, altinity-in-ash, altinity-image-x86-app-docker-ce]
  #   if: ${{ always() }}
  #   needs: [KeeperJepsenRelease]
  #   steps:
  #     - name: Set envs
  #       run: |
  #         cat >> "$GITHUB_ENV" << 'EOF'
  #         TEMP_PATH=${{runner.temp}}/server_jepsen
  #         REPO_COPY=${{runner.temp}}/server_jepsen/ClickHouse
  #         EOF
  #     - name: Check out repository code
  #       uses: ClickHouse/checkout@v1
  #       with:
  #         clear-repository: true
  #         fetch-depth: 0
  #     - name: Jepsen Test
  #       run: |
  #         sudo rm -fr "$TEMP_PATH"
  #         mkdir -p "$TEMP_PATH"
  #         cp -r "$GITHUB_WORKSPACE" "$TEMP_PATH"
  #         cd "$REPO_COPY/tests/ci"
  #         python3 jepsen_check.py server
  #     - name: Cleanup
  #       if: always()
  #       run: |
  #         docker ps --quiet | xargs --no-run-if-empty docker kill ||:
  #         docker ps --all --quiet | xargs --no-run-if-empty docker rm -f ||:
  #         sudo rm -fr "$TEMP_PATH"
