name: JepsenWorkflow
env:
  # Force the stdout and stderr streams to be unbuffered
  PYTHONUNBUFFERED: 1
concurrency:
  group: jepsen
on: # yamllint disable-line rule:truthy
#   schedule:
#     - cron: '0 */6 * * *'
  workflow_dispatch:
  workflow_call:
jobs:
  KeeperJepsenRelease:
    runs-on: [self-hosted, altinity-on-demand, altinity-type-cpx41, altinity-in-ash, altinity-image-x86-app-docker-ce]
    with:
      test_name: Jepsen keeper check
      runner_type: style-checker
      run_command: |
        cd "$REPO_COPY/tests/ci"
        python3 jepsen_check.py keeper
  # ServerJepsenRelease:
  #   runs-on: [self-hosted, altinity-on-demand, altinity-type-cpx41, altinity-in-ash, altinity-image-x86-app-docker-ce]
  #   uses: ./.github/workflows/reusable_test.yml
  #   with:
  #     test_name: Jepsen server check
  #     runner_type: style-checker
  #     run_command: |
  #       cd "$REPO_COPY/tests/ci"
  #       python3 jepsen_check.py server
