name: MasterCI

env:
  PYTHONUNBUFFERED: 1

on:
  push:
    branches:
      - 'master'

jobs:
  Check_env_vars:
    runs-on: [self-hosted, style-checker]
    steps:
      - name: Check out repository code
        uses: ClickHouse/checkout@v1
        with:
          clear-repository: true
      - run: ./check-env-vars.yml
