name: Sign and Release packages

on:
  workflow_dispatch:

env:
  ARTIFACT_NAME: build_report_package_release
  AWS_REGION: us-east-1
  SRC_BUCKET: altinity-build-artifacts
  S3_STORAGE_BUCKET: altinity-test-reports

jobs:

  sign-and-publish:
    runs-on: arc-runners-clickhouse-signer-prod
    steps:
      - run: ls /home/runner/.cache/

      - name: check production dir
        run: /home/runner/.cache/production/

      - name: check prod dir
        run: /home/runner/.cache/prod/
