name: Sign and Release packages
on: workflow_dispatch
jobs:
  test-job:
    runs-on: arc-runners-clickhouse-signer-prod
    steps:
      - uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2
          arch: arm64

      - name: Upload to prod
        run: |
          aws s3 sync /home/runner/.cache/bin-repo/ s3://builds.altinity.cloud/Green/bin-repo
