name: Sign and Release packages

on:
  workflow_dispatch:

jobs:
  sign-and-publish:
    runs-on: arc-runners-clickhouse-signer-prod
    steps:
      # - name: Install aws cli
      #   uses: unfor19/install-aws-cli-action@v1
      #   with:
      #     version: 2
      #     arch: arm64
      - run: apt-ftparchive contents /home/runner/.cache/productio/apt-repo/pool/main > Contents-test
      - run: cat Contents-test
      - run: ls -la /home/runner/.cache/production/apt-repo/dists/stable 
